##import turtle
##sam=turtle.Turtle()
##sam.shape('turtle')
##
##sam.color("blue")
##sam.pensize(5)
##sam.write("what color am I now?")
##sam.left(45)
##sam.forward(100)
##
##sam.color("red")
##sam.write("what color am I now?")
##sam.left(45)
##sam.forward(100)
##
##sam.color("orange")
##sam.write("what color am I now?")
##sam.left(45)
##sam.forward(100)
##
##sam.color("pink")
##sam.write("what color am I now?")
##sam.left(45)
##sam.forward(100)
##
##sam.color("violet")
##sam.write("what color am I now?")
##sam.left(45)
##sam.forward(100)
##
##sam.color("brown")
##sam.write("what color am I now?")
##sam.left(45)
##sam.forward(100)
##
##sam.color("pink")
##sam.write("what color am I now?")
##sam.left(45)
##sam.forward(100)
##
##sam.color("dark green")
##sam.write("what color am I now?")
##sam.left(45)
##sam.forward(100)


##import turtle
##sam=turtle.Turtle()
##sam.shape('turtle')
##
##sam.pensize(5)
##sam.color("light blue")
##sam.forward(100)
##sam.backward(100)
##sam.right(90)
##sam.forward(60)
##sam.left(90)
##sam.forward(100)
##sam.backward(100)
##sam.right(90)
##sam.forward(60)
##sam.left(90)
##sam.forward(100)
##
##sam.penup()
##sam.backward(250)
##sam.pendown()
##sam.left(60)
##sam.forward(140)
##sam.right(120)
##sam.forward(140)
##sam.backward(70)
##sam.right(120)
##sam.forward(70)
##
##import turtle
##sam=turtle.Turtle()
##sam.shape('turtle')
##sam.pensize(5)
##sam.color("orange")
##
##sam.penup()
##sam.backward(100)
##sam.pendown()
##sam.right(60)
##sam.forward(100)
##sam.left(120)
##sam.forward(100)
##
##sam.penup()
##sam.right(60)
##sam.forward(40)
##sam.pendown()
##sam.forward(100)
##sam.backward(50)
##sam.right(90)
##sam.forward(100)
##sam.left(90)
##sam.backward(50)
##sam.left(90)
##sam.forward(10)
##sam.penup()
##sam.right(90)
##sam.forward(300)
