##import turtle
##sam=turtle.Turtle()
##sam.shape('turtle')
##sam.color("green")
##sam.pensize(10)
##
##sam.left(45)
##sam.forward(60)
##sam.backward(120)
##sam.forward(60)
##sam.right(90)
##sam.forward(60)
##sam.backward(120)

import turtle
sam=turtle.Turtle()
sam.shape('turtle')
sam.color("blue")
sam.pensize(5)

sam.penup()
sam.backward(50)
sam.right(90)
sam.forward(30)
sam.pendown()
sam.left(150)
sam.forward(120)
sam.right(120)
sam.forward(120)
sam.backward(60)
sam.right(120)
sam.forward(60)

sam.penup()
sam.backward(120)
sam.pendown()
sam.forward(30)

sam.penup()
sam.backward(70)
sam.right(90)
sam.forward(50)
sam.left(90)
sam.forward(30)
sam.left(180)
sam.pendown()

sam.forward(80)
sam.right(130)
sam.forward(130)
sam.left(130)
sam.forward(80)

import turtle
sam=turtle.Turtle()
sam.shape('turtle')
sam.pensize(5)
sam.penup()
sam.backward(200)
sam.left(90)
sam.forward(50)
sam.right(150)
sam.pendown()

sam.color("red")
sam.forward(100)
sam.left(120)
sam.forward(100)
sam.penup()
sam.right(60)
sam.forward(30)
sam.right(90)
sam.forward(85)
sam.right(180)

sam.pendown()
sam.color("blue")
sam.forward(40)
sam.penup()
sam.forward(20)
sam.pendown()
sam.forward(10)
sam.penup()
sam.right(90)
sam.forward(35)
sam.right(90)
sam.forward(30)
sam.left(20)
sam.pendown()

sam.color("yellow")
sam.forward(50)
sam.left(130)
sam.forward(50)
sam.penup()
sam.right(60)
sam.forward(30)
sam.right(90)
sam.pendown()

sam.color("orange")
sam.forward(40)
sam.left(90)
sam.forward(40)
sam.left(90)
sam.forward(40)
sam.left(90)
sam.forward(40)
sam.left(180)
sam.forward(40)
sam.right(90)
sam.forward(40)
sam.left(90)
sam.forward(15)
sam.penup()
sam.forward(30)
sam.left(90)
sam.pendown()

sam.color("purple")
sam.forward(40)
sam.left(90)
sam.forward(10)
sam.backward(50)
sam.left(90)
sam.forward(40)

