##import turtle
##sam=turtle.Turtle()
##sam.shape('turtle')
##
##sam.penup()
##sam.write("I start at 0,0")
##sam.goto(100,100)
##sam.write("This is 100,100.")
##sam.goto(-100,-100)
##sam.write("This is -100,-100.")
##sam.goto(100,-100)
##sam.write("This is 100,-100")
##sam.goto(-100,100)
##sam.write("This is -100,100")

##import turtle
##sam=turtle.Turtle()
##sam.shape('turtle')
##sam.penup()
##sam.goto(200,200)
##sam.goto(-200,200)
##sam.goto(200,-200)
##sam.goto(-200,-200)
##sam.write("This is how big my grid is. Yay")

import turtle
sam=turtle.Turtle()
sam.shape('turtle')
sam.pencolor('red')
sam.pensize(5)
sam.fillcolor('blue')
sam.begin_fill()
sam.circle(100)
sam.end_fill()
sam.penup()

sam.left(90)
sam.forward(10)
sam.right(90)
sam.pendown()

sam.fillcolor("dark red")
sam.begin_fill()
sam.circle(35)
sam.end_fill()
sam.penup()

sam.left(90)
sam.forward(140)
sam.left(90)
sam.forward(40)
sam.pendown()

sam.fillcolor("white")
sam.begin_fill()
sam.circle(25)
sam.end_fill()
sam.penup()

sam.left(90)
sam.forward(25)
sam.right(90)
sam.pendown()

sam.pencolor("black")
sam.fillcolor("black")
sam.begin_fill()
sam.circle(10)
sam.end_fill()
sam.penup()

sam.left(90)
sam.forward(30)
sam.left(90)
sam.forward(70)
sam.pendown()

sam.pencolor('red')
sam.fillcolor("white")
sam.begin_fill()
sam.circle(35)
sam.end_fill()
sam.penup()

sam.left(90)
sam.forward(25)
sam.left(90)
sam.forward(12)
sam.pendown()

sam.pencolor("black")
sam.fillcolor("black")
sam.begin_fill()
sam.circle(10)
sam.end_fill()
