import turtle
sam=turtle.Turtle()
sam.shape('turtle')
window=turtle.Screen()
window.bgcolor("lightblue")
sam.penup()
sam.goto(0,-500)

sam.fillcolor("red")
sam.color("red")
sam.begin_fill()
sam.circle(180)
sam.end_fill()

sam.fillcolor("orange")
sam.color("orange")
sam.begin_fill()
sam.circle(170)
sam.end_fill()

sam.fillcolor("yellow")
sam.color("yellow")
sam.begin_fill()
sam.circle(160)
sam.end_fill()

sam.fillcolor("green")
sam.color("green")
sam.begin_fill()
sam.circle(150)
sam.end_fill()

sam.fillcolor("blue")
sam.color("blue")
sam.begin_fill()
sam.circle(140)
sam.end_fill()

sam.fillcolor("purple")
sam.color("purple")
sam.begin_fill()
sam.circle(130)
sam.end_fill()

sam.begin_fill()
sam.fillcolor("lightblue")
sam.circle(120)
sam.end_fill()
